// File: DFFSyncCenter.v
// Generated by MyHDL 0.9.0
// Date: Thu Oct 26 01:02:57 2017


`timescale 1ns/10ps

module DFFSyncCenter (
    D_in,
    Q_out,
    Qn_out,
    clk
);


input D_in;
output Q_out;
reg Q_out;
output Qn_out;
reg Qn_out;
input clk;






always @(clk) begin: DFFSYNCCENTER_LOGIC
    Q_out <= D_in;
    Qn_out <= (!D_in);
end

endmodule
