// File: DLatch.v
// Generated by MyHDL 0.9.0
// Date: Thu Oct 26 00:40:46 2017


`timescale 1ns/10ps

module DLatch (
    D_in,
    ena,
    Q_out,
    Qn_out
);


input D_in;
input ena;
output Q_out;
reg Q_out;
output Qn_out;
reg Qn_out;






always @(ena, D_in) begin: DLATCH_LOGIC
    if (ena) begin
        Q_out = D_in;
        Qn_out = (!D_in);
    end
end

endmodule
