// File: GSRLatch.v
// Generated by MyHDL 0.9.0
// Date: Thu Oct 26 00:40:44 2017


`timescale 1ns/10ps

module GSRLatch (
    S_in,
    rst,
    ena,
    Q_out,
    Qn_out
);


input S_in;
input rst;
input ena;
output Q_out;
reg Q_out;
output Qn_out;
reg Qn_out;






always @(ena, S_in, rst) begin: GSRLATCH_LOGIC
    if (ena) begin
        if ((S_in && (rst == 0))) begin
            Q_out = 1;
            Qn_out = 0;
        end
        else if (((S_in == 0) && rst)) begin
            Q_out = 0;
            Qn_out = 1;
        end
        else if ((S_in && rst)) begin
            Q_out = 0;
            Qn_out = 0;
        end
    end
    else begin
        // pass
    end
end

endmodule
