// File: HalfAdder.v
// Generated by MyHDL 0.9.0
// Date: Mon Oct  9 19:20:28 2017


`timescale 1ns/10ps

module HalfAdder (
    x_1in,
    x_2in,
    S_out,
    C_out
);


input x_1in;
input x_2in;
output S_out;
wire S_out;
output C_out;
wire C_out;







assign S_out = (x_1in ^ x_2in);
assign C_out = (x_1in & x_2in);

endmodule
