// File: IntCurde.v
// Generated by MyHDL 0.9.0
// Date: Mon Oct  9 19:20:40 2017


`timescale 1ns/10ps

module IntCurde (
    x_in,
    y_out,
    clk,
    rst
);


input signed [4:0] x_in;
output signed [6:0] y_out;
reg signed [6:0] y_out;
input clk;
input rst;






always @(posedge clk) begin: INTCURDE_LOGIC
    if (rst) begin
        y_out <= 0;
    end
    else begin
        y_out <= (x_in + y_out);
    end
end

endmodule
