// File: MultiplyBehavioral.v
// Generated by MyHDL 0.9.0
// Date: Mon Oct  9 19:20:33 2017


`timescale 1ns/10ps

module MultiplyBehavioral (
    x_1in,
    x_2in,
    P_out
);


input [2:0] x_1in;
input [2:0] x_2in;
output [8:0] P_out;
wire [8:0] P_out;







assign P_out = (x_1in * x_2in);

endmodule
