// File: mux21_gates.v
// Generated by MyHDL 0.9.0
// Date: Mon Oct  9 19:21:43 2017


`timescale 1ns/10ps

module mux21_gates (
    sel,
    x_1in,
    x_2in,
    f_out
);


input sel;
input x_1in;
input x_2in;
output f_out;
wire f_out;







assign f_out = ((sel && x_2in) || (x_1in && (!sel)));

endmodule
