// File: MUX41_gates.v
// Generated by MyHDL 0.9.0
// Date: Mon Oct  9 19:21:50 2017


`timescale 1ns/10ps

module MUX41_gates (
    sel_1,
    sel_2,
    x_1in,
    x_2in,
    x_3in,
    x_4in,
    f_out
);


input sel_1;
input sel_2;
input x_1in;
input x_2in;
input x_3in;
input x_4in;
output f_out;
wire f_out;







assign f_out = (((!sel_1) && (!sel_2) && x_1in) || ((!sel_1) && sel_2 && x_2in) || (sel_1 && (!sel_2) && x_3in) || (sel_1 && sel_2 && x_4in));

endmodule
