// File: MUX41_behavioralVec.v
// Generated by MyHDL 0.10
// Date: Sat Jul  7 01:27:41 2018


`timescale 1ns/10ps

module MUX41_behavioralVec (
    sel,
    x_in,
    f_out
);


input [1:0] sel;
input [3:0] x_in;
output f_out;
wire f_out;





assign f_out = x_in[sel];

endmodule
