// File: MUX41_behavioralVec.v
// Generated by MyHDL 0.9.0
// Date: Mon Oct  9 19:21:58 2017


`timescale 1ns/10ps

module MUX41_behavioralVec (
    sel,
    x_in,
    f_out
);


input [1:0] sel;
input [3:0] x_in;
output f_out;
wire f_out;







assign f_out = x_in[sel];

endmodule
