-- File: NotGate.vhd
-- Generated by MyHDL 0.9.0
-- Date: Mon Oct  9 02:48:20 2017


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity NotGate is
    port (
        x_in: in std_logic;
        y_out: out std_logic
    );
end entity NotGate;
-- Not Logic Gate myHDL Module (function)
-- 
-- Args:
--     x_in: bool Input port
--     y_out: bool Output port
-- 
-- Returns:
--     NOT Combo logic operation
--     

architecture MyHDL of NotGate is






begin






y_out <= stdl((not bool(x_in)));

end architecture MyHDL;
