// File: NotGate.v
// Generated by MyHDL 0.9.0
// Date: Mon Oct  9 02:48:20 2017


`timescale 1ns/10ps

module NotGate (
    x_in,
    y_out
);
// Not Logic Gate myHDL Module (function)
// 
// Args:
//     x_in: bool Input port
//     y_out: bool Output port
// 
// Returns:
//     NOT Combo logic operation
//     

input x_in;
output y_out;
wire y_out;







assign y_out = (!x_in);

endmodule
