// File: Shannon21MUX.v
// Generated by MyHDL 0.9.0
// Date: Mon Oct  9 19:22:03 2017


`timescale 1ns/10ps

module Shannon21MUX (
    s1,
    s2,
    w_3in,
    f_out
);


input s1;
input s2;
input w_3in;
output f_out;
reg f_out;






always @(s2, s1, w_3in) begin: SHANNON21MUX_LOGIC
    if (((!s1) && (!s2))) begin
        f_out = (!w_3in);
    end
    else if (((!s1) && s2)) begin
        f_out = (!w_3in);
    end
    else if ((s1 && (!s2))) begin
        f_out = w_3in;
    end
    else begin
        f_out = 1;
    end
end

endmodule
