// File: SRLatch.v
// Generated by MyHDL 0.9.0
// Date: Thu Oct 26 00:40:43 2017


`timescale 1ns/10ps

module SRLatch (
    S_in,
    rst,
    Q_out,
    Qn_out
);


input S_in;
input rst;
output Q_out;
reg Q_out;
output Qn_out;
reg Qn_out;






always @(rst, S_in) begin: SRLATCH_LOGIC
    if ((S_in && (rst == 0))) begin
        Q_out = 1;
        Qn_out = 0;
    end
    else if (((S_in == 0) && rst)) begin
        Q_out = 0;
        Qn_out = 1;
    end
    else if ((S_in && rst)) begin
        Q_out = 0;
        Qn_out = 0;
    end
end

endmodule
