// File: SuptractionBehavioral.v
// Generated by MyHDL 0.9.0
// Date: Mon Oct  9 19:20:32 2017


`timescale 1ns/10ps

module SuptractionBehavioral (
    x_1in,
    x_2in,
    S_out
);


input [2:0] x_1in;
input [2:0] x_2in;
output signed [3:0] S_out;
wire signed [3:0] S_out;







assign S_out = (x_1in - x_2in);

endmodule
