// File: BitslicingDemo_TB_V_VHDL.v
// Generated by MyHDL 0.10
// Date: Wed Aug 29 14:28:07 2018


`timescale 1ns/10ps

module BitslicingDemo_TB_V_VHDL (

);
// myHDL -> Verilog/VHDL Testbench for `BitSlicingDemo`


wire signed [15:0] Res;
reg [4:0] MSB = 16;
reg [4:0] LSB = 0;
wire [15:0] BitSlicingDemo0_0_RefVal;

assign BitSlicingDemo0_0_RefVal = 16'd-1749;


always @(LSB, MSB, Res) begin: BITSLICINGDEMO_TB_V_VHDL_PRINT_DATA
    $write("%h", MSB);
    $write(" ");
    $write("%h", LSB);
    $write(" ");
    $write("%h", Res);
    $write("\n");
end



assign Res = $signed(BitSlicingDemo0_0_RefVal[MSB-1:LSB]);


initial begin: BITSLICINGDEMO_TB_V_VHDL_STIMULES
    integer j;
    for (j=0; j<15; j=j+1) begin
        MSB <= 16;
        LSB <= j;
        # 1;
    end
    $finish;
end

endmodule
