// File: BitSlicingDemo.v
// Generated by MyHDL 0.10
// Date: Wed Aug 29 14:28:06 2018


`timescale 1ns/10ps

module BitSlicingDemo (
    MSB,
    LSB,
    Res
);
// Demenstration Module for Bit Slicing in myHDL
// 
// Inputs:
//     MSB (5BitVec): Most Signficant Bit Index Must be > LSB, 
//         ex: if LSB==0 MSB must range between 1 and 15
//     LSB (5BitVec): Lest Signficant Bit Index Must be < MSB
//         ex: if MSB==15 LSB must range beteen 0 and 15
// 
// Outputs:
//     Res(16BitVec Signed): Result of the slicing operation from
//     Refrance Vales (hard coded in module) -1749 (16BitVec Signed)
//     

input [4:0] MSB;
input [4:0] LSB;
output signed [15:0] Res;
wire signed [15:0] Res;

wire [15:0] RefVal;

assign RefVal = -16'd1749;



assign Res = $signed(RefVal[MSB-1:LSB]);

endmodule
