// File: BitSelectDemo.v
// Generated by MyHDL 0.10
// Date: Wed Aug 29 14:27:57 2018


`timescale 1ns/10ps

module BitSelectDemo (
    Index,
    Res,
    SignRes
);
// Bit Selection Demo
// 
// Input:
//     Index(4BitVec): value for selection from internal refrances 
// Output:
//     Res(8BitVec): BitVector with Bit Location set from `Index` from 
//         refrance internal 8Bit `intbv` with value 93
//     SignRes(8BitVec Signed): signed BitVector with Bit Location set from `Index` from 
//         refrance internal signed 8Bit `intbv` with value -93

input [3:0] Index;
output [7:0] Res;
reg [7:0] Res;
output signed [7:0] SignRes;
reg signed [7:0] SignRes;

wire [7:0] RefS;
wire [7:0] Ref;

assign RefS = -8'd93;
assign Ref = 8'd93;


always @(Index, RefS, Ref) begin: BITSELECTDEMO_LOGIC
    Res[Index] = Ref[Index];
    SignRes[Index] = RefS[Index];
end

endmodule
