-- File: BitslicingDemo_TB_V_VHDL.vhd
-- Generated by MyHDL 0.10
-- Date: Wed Aug 29 14:28:07 2018


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_010.all;

entity BitslicingDemo_TB_V_VHDL is
end entity BitslicingDemo_TB_V_VHDL;
-- myHDL -> Verilog/VHDL Testbench for `BitSlicingDemo`

architecture MyHDL of BitslicingDemo_TB_V_VHDL is


signal Res: signed (15 downto 0) := 16X"0000";
signal MSB: unsigned(4 downto 0) := 5X"10";
signal LSB: unsigned(4 downto 0) := 5X"00";
signal BitSlicingDemo0_0_RefVal: signed (15 downto 0);

begin


BitSlicingDemo0_0_RefVal <= to_signed(-1749, 16);


BITSLICINGDEMO_TB_V_VHDL_PRINT_DATA: process (LSB, MSB, Res) is
    variable L: line;
begin
    write(L, to_hstring(MSB));
    write(L, string'(" "));
    write(L, to_hstring(LSB));
    write(L, string'(" "));
    write(L, to_hstring(unsigned(Res)));
    writeline(output, L);
end process BITSLICINGDEMO_TB_V_VHDL_PRINT_DATA;


Res <= signed(unsigned(BitSlicingDemo0_0_RefVal(to_integer(MSB)-1 downto to_integer(LSB))));

BITSLICINGDEMO_TB_V_VHDL_STIMULES: process is
begin
    for j in 0 to 15-1 loop
        MSB <= to_unsigned(16, 5);
        LSB <= to_unsigned(j, 5);
        wait for 1 * 1 ns;
    end loop;
    assert False report "End of Simulation" severity Failure;
    wait;
end process BITSLICINGDEMO_TB_V_VHDL_STIMULES;

end architecture MyHDL;
