// File: BitSelectDemo_TB_V_VHDL.v
// Generated by MyHDL 0.10
// Date: Wed Aug 29 14:27:58 2018


`timescale 1ns/10ps

module BitSelectDemo_TB_V_VHDL (

);
// myHDL -> Verilog/VHDL Testbench


reg [3:0] Index = 0;
reg [7:0] Res = 0;
reg signed [7:0] SignRes = 0;
wire [7:0] BitSelectDemo0_0_RefS;
wire [7:0] BitSelectDemo0_0_Ref;

assign BitSelectDemo0_0_RefS = -8'd93;
assign BitSelectDemo0_0_Ref = 8'd93;


always @(SignRes, Index, Res) begin: BITSELECTDEMO_TB_V_VHDL_PRINT_DATA
    $write("%h", Index);
    $write(" ");
    $write("%h", Res);
    $write(" ");
    $write("%h", SignRes);
    $write("\n");
end


always @(Index, BitSelectDemo0_0_RefS, BitSelectDemo0_0_Ref) begin: BITSELECTDEMO_TB_V_VHDL_BITSELECTDEMO0_0_LOGIC
    Res[Index] = BitSelectDemo0_0_Ref[Index];
    SignRes[Index] = BitSelectDemo0_0_RefS[Index];
end


initial begin: BITSELECTDEMO_TB_V_VHDL_STIMULES
    integer i;
    for (i=0; i<7; i=i+1) begin
        Index <= i;
        # 1;
    end
    $finish;
end

endmodule
