-- File: BitSelectDemo.vhd
-- Generated by MyHDL 0.10
-- Date: Wed Aug 29 14:27:57 2018


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_010.all;

entity BitSelectDemo is
    port (
        Index: in unsigned(3 downto 0);
        Res: out unsigned(7 downto 0);
        SignRes: out signed (7 downto 0)
    );
end entity BitSelectDemo;
-- Bit Selection Demo
-- 
-- Input:
--     Index(4BitVec): value for selection from internal refrances 
-- Output:
--     Res(8BitVec): BitVector with Bit Location set from `Index` from 
--         refrance internal 8Bit `intbv` with value 93
--     SignRes(8BitVec Signed): signed BitVector with Bit Location set from `Index` from 
--         refrance internal signed 8Bit `intbv` with value -93

architecture MyHDL of BitSelectDemo is


signal RefS: signed (7 downto 0);
signal Ref: unsigned(7 downto 0);

begin


RefS <= to_signed(-93, 8);
Ref <= to_unsigned(93, 8);


BITSELECTDEMO_LOGIC: process (Index, RefS, Ref) is
begin
    Res(to_integer(Index)) <= Ref(to_integer(Index));
    SignRes(to_integer(Index)) <= RefS(to_integer(Index));
end process BITSELECTDEMO_LOGIC;

end architecture MyHDL;
