-- File: BitSlicingDemo.vhd
-- Generated by MyHDL 0.10
-- Date: Wed Aug 29 14:28:06 2018


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_010.all;

entity BitSlicingDemo is
    port (
        MSB: in unsigned(4 downto 0);
        LSB: in unsigned(4 downto 0);
        Res: out signed (15 downto 0)
    );
end entity BitSlicingDemo;
-- Demenstration Module for Bit Slicing in myHDL
-- 
-- Inputs:
--     MSB (5BitVec): Most Signficant Bit Index Must be > LSB, 
--         ex: if LSB==0 MSB must range between 1 and 15
--     LSB (5BitVec): Lest Signficant Bit Index Must be < MSB
--         ex: if MSB==15 LSB must range beteen 0 and 15
-- 
-- Outputs:
--     Res(16BitVec Signed): Result of the slicing operation from
--     Refrance Vales (hard coded in module) -1749 (16BitVec Signed)
--     

architecture MyHDL of BitSlicingDemo is


signal RefVal: signed (15 downto 0);

begin


RefVal <= to_signed(-1749, 16);



Res <= signed(unsigned(RefVal(to_integer(MSB)-1 downto to_integer(LSB))));

end architecture MyHDL;
