-- File: BitSelectDemo_TB_V_VHDL.vhd
-- Generated by MyHDL 0.10
-- Date: Wed Aug 29 14:27:58 2018


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_010.all;

entity BitSelectDemo_TB_V_VHDL is
end entity BitSelectDemo_TB_V_VHDL;
-- myHDL -> Verilog/VHDL Testbench

architecture MyHDL of BitSelectDemo_TB_V_VHDL is


signal Index: unsigned(3 downto 0) := 4X"0";
signal Res: unsigned(7 downto 0) := 8X"00";
signal SignRes: signed (7 downto 0) := 8X"00";
signal BitSelectDemo0_0_RefS: signed (7 downto 0);
signal BitSelectDemo0_0_Ref: unsigned(7 downto 0);

begin


BitSelectDemo0_0_RefS <= to_signed(-93, 8);
BitSelectDemo0_0_Ref <= to_unsigned(93, 8);


BITSELECTDEMO_TB_V_VHDL_PRINT_DATA: process (SignRes, Index, Res) is
    variable L: line;
begin
    write(L, to_hstring(Index));
    write(L, string'(" "));
    write(L, to_hstring(Res));
    write(L, string'(" "));
    write(L, to_hstring(unsigned(SignRes)));
    writeline(output, L);
end process BITSELECTDEMO_TB_V_VHDL_PRINT_DATA;

BITSELECTDEMO_TB_V_VHDL_BITSELECTDEMO0_0_LOGIC: process (Index, BitSelectDemo0_0_RefS, BitSelectDemo0_0_Ref) is
begin
    Res(to_integer(Index)) <= BitSelectDemo0_0_Ref(to_integer(Index));
    SignRes(to_integer(Index)) <= BitSelectDemo0_0_RefS(to_integer(Index));
end process BITSELECTDEMO_TB_V_VHDL_BITSELECTDEMO0_0_LOGIC;

BITSELECTDEMO_TB_V_VHDL_STIMULES: process is
begin
    for i in 0 to 7-1 loop
        Index <= to_unsigned(i, 4);
        wait for 1 * 1 ns;
    end loop;
    assert False report "End of Simulation" severity Failure;
    wait;
end process BITSELECTDEMO_TB_V_VHDL_STIMULES;

end architecture MyHDL;
