// File: ConcatDemo.v
// Generated by MyHDL 0.10
// Date: Wed Aug 29 14:28:03 2018


`timescale 1ns/10ps

module ConcatDemo (
    Res,
    ResS
);
// `concat` demo 
// Input:
//     None
// Ouput:
//     Res(7BitVec): concat result
//     Res(7BitVec Signed): concat result that is signed

output [6:0] Res;
wire [6:0] Res;
output signed [6:0] ResS;
wire signed [6:0] ResS;

wire [5:0] RefVal;

assign RefVal = 6'd25;



assign Res = {1'b1, RefVal};
assign ResS = $signed({1'b1, RefVal});

endmodule
