-- File: ConcatDemo.vhd
-- Generated by MyHDL 0.10
-- Date: Wed Aug 29 14:28:03 2018


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_010.all;

entity ConcatDemo is
    port (
        Res: out unsigned(6 downto 0);
        ResS: out signed (6 downto 0)
    );
end entity ConcatDemo;
-- `concat` demo 
-- Input:
--     None
-- Ouput:
--     Res(7BitVec): concat result
--     Res(7BitVec Signed): concat result that is signed

architecture MyHDL of ConcatDemo is


signal RefVal: unsigned(5 downto 0);

begin


RefVal <= to_unsigned(25, 6);



Res <= unsigned'('1' & RefVal);
ResS <= signed(unsigned'('1' & RefVal));

end architecture MyHDL;
