// File: ShiftingDemo_TB_V_VHDL.v
// Generated by MyHDL 0.10
// Date: Wed Aug 29 14:28:02 2018


`timescale 1ns/10ps

module ShiftingDemo_TB_V_VHDL (

);
// myHDL -> verilog/VHDL testbench for `ShiftingDemo`


wire signed [14:0] LSRes;
reg [3:0] ShiftVal = 0;
wire signed [7:0] RSRes;
wire [7:0] ShiftingDemo0_0_RefVal;

assign ShiftingDemo0_0_RefVal = -8'd55;


always @(ShiftVal, RSRes, LSRes) begin: SHIFTINGDEMO_TB_V_VHDL_PRINT_DATA
    $write("%h", ShiftVal);
    $write(" ");
    $write("%h", RSRes);
    $write(" ");
    $write("%h", LSRes);
    $write("\n");
end



assign RSRes = $signed(ShiftingDemo0_0_RefVal >>> $signed({1'b0, ShiftVal}));
assign LSRes = (ShiftingDemo0_0_RefVal << $signed({1'b0, ShiftVal}));


initial begin: SHIFTINGDEMO_TB_V_VHDL_STIMULES
    integer i;
    for (i=0; i<8; i=i+1) begin
        ShiftVal <= i;
        # 1;
    end
    $finish;
end

endmodule
