-- File: ShiftingDemo_TB_V_VHDL.vhd
-- Generated by MyHDL 0.10
-- Date: Wed Aug 29 14:28:02 2018


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_010.all;

entity ShiftingDemo_TB_V_VHDL is
end entity ShiftingDemo_TB_V_VHDL;
-- myHDL -> verilog/VHDL testbench for `ShiftingDemo`

architecture MyHDL of ShiftingDemo_TB_V_VHDL is


signal LSRes: signed (14 downto 0) := 15X"0000";
signal ShiftVal: unsigned(3 downto 0) := 4X"0";
signal RSRes: signed (7 downto 0) := 8X"00";
signal ShiftingDemo0_0_RefVal: signed (7 downto 0);

begin


ShiftingDemo0_0_RefVal <= to_signed(-55, 8);


SHIFTINGDEMO_TB_V_VHDL_PRINT_DATA: process (ShiftVal, RSRes, LSRes) is
    variable L: line;
begin
    write(L, to_hstring(ShiftVal));
    write(L, string'(" "));
    write(L, to_hstring(unsigned(RSRes)));
    write(L, string'(" "));
    write(L, to_hstring(unsigned(LSRes)));
    writeline(output, L);
end process SHIFTINGDEMO_TB_V_VHDL_PRINT_DATA;


RSRes <= shift_right(ShiftingDemo0_0_RefVal, to_integer(ShiftVal));
LSRes <= shift_left(resize(ShiftingDemo0_0_RefVal, 15), to_integer(ShiftVal));

SHIFTINGDEMO_TB_V_VHDL_STIMULES: process is
begin
    for i in 0 to 8-1 loop
        ShiftVal <= to_unsigned(i, 4);
        wait for 1 * 1 ns;
    end loop;
    assert False report "End of Simulation" severity Failure;
    wait;
end process SHIFTINGDEMO_TB_V_VHDL_STIMULES;

end architecture MyHDL;
