// File: ShiftingDemo.v
// Generated by MyHDL 0.10
// Date: Wed Aug 29 14:28:01 2018


`timescale 1ns/10ps

module ShiftingDemo (
    ShiftVal,
    RSRes,
    LSRes
);
// Module to Demo Shifting Behavior in myHDL refrance value
// -55 8Bit
// 
// Input:
//     ShiftVal(4BitVec): shift amount, for this demo to not
//         use values greater then 7
// Output:
//     RSRes(8BitVec Signed): output of Right Shifting 
//     LSRes (15BitVec Signed): output of Left Shifting

input [3:0] ShiftVal;
output signed [7:0] RSRes;
wire signed [7:0] RSRes;
output signed [14:0] LSRes;
wire signed [14:0] LSRes;

wire [7:0] RefVal;

assign RefVal = -8'd55;



assign RSRes = $signed(RefVal >>> $signed({1'b0, ShiftVal}));
assign LSRes = (RefVal << $signed({1'b0, ShiftVal}));

endmodule
