// File: BDCLed.v
// Generated by MyHDL 0.10
// Date: Mon Aug 20 12:44:39 2018


`timescale 1ns/10ps

module BDCLed (
    clk,
    led
);
// FPGA Hello world of counter duty cycle led brightness control
// https://timetoexplore.net/blog/arty-fpga-verilog-02
// 
// Target:
//     ZYNQ 7000 Board (Arty, PYNQ-Z1, PYNQ-Z2) with at least 4 leds
// 
// 
// Input:
//     clk(bool): clock input    
// Ouput:
//     led(4bitVec): led output to PYNQ-Z1/2 (ect.)
//     

input clk;
output [3:0] led;
reg [3:0] led;

wire [7:0] duty_led;
reg [7:0] counter = 0;

assign duty_led = 8'd8;


always @(posedge clk) begin: BDCLED_LOGIC
    counter <= (counter + 1);
    if ((counter < duty_led)) begin
        led <= 15;
    end
    else begin
        led <= 0;
    end
end

endmodule
