// File: countLED.v
// Generated by MyHDL 0.10
// Date: Mon Aug 20 12:44:11 2018


`timescale 1ns/10ps

module countLED (
    clk,
    led
);
// FPGA Hello world of counter sampled led pulsing from
// https://timetoexplore.net/blog/arty-fpga-verilog-02
// 
// Target:
//     ZYNQ 7000 Board (Arty, PYNQ-Z1, PYNQ-Z2) with at least 2 
//     switchs and 4 leds
// 
// 
// Input:
//     clk(bool): clock input    
// Ouput:
//     led(4bitVec): led output to PYNQ-Z1/2 (ect.)
//     

input clk;
output [3:0] led;
reg [3:0] led;

reg [32:0] counter = 0;



always @(posedge clk) begin: COUNTLED_LOGIC
    counter <= (counter + 1);
    led[0] <= counter[26];
    led[1] <= counter[24];
    led[2] <= counter[22];
    led[3] <= counter[20];
end

endmodule
