// File: pwm.v
// Generated by MyHDL 0.10
// Date: Mon Aug 20 11:53:44 2018


`timescale 1ns/10ps

module pwm (
    clk,
    dutyCount,
    ofState
);
// pwm module
// 
// Inputs:
//     clk(bool): clock
//     dutyCount(bitVec): clock cycle percent on time value
//     using an 8Bit internal counter
//     
// Ouputs:
//     ofState(bool): on/off state signal of the PWM

input clk;
input [7:0] dutyCount;
output ofState;
reg ofState;

reg [7:0] counter = 0;



always @(posedge clk) begin: PWM_LOGIC
    counter <= (counter + 1);
    ofState <= (counter < dutyCount);
end

endmodule
