// File: SlowClock.v
// Generated by MyHDL 0.9.0
// Date: Wed Feb  7 15:26:37 2018


`timescale 1ns/10ps

module SlowClock (
    FastClk,
    SlowClk,
    rst
);


input FastClk;
output SlowClk;
reg SlowClk;
input rst;

reg [14:0] ClkCounter;





always @(posedge FastClk, negedge rst) begin: SLOWCLOCK_LOGIC
    if (rst) begin
        ClkCounter <= 0;
    end
    else begin
        if (($signed({1'b0, ClkCounter}) == ((2 ** 15) - 1))) begin
            SlowClk <= 1;
        end
        else begin
            SlowClk <= 0;
            ClkCounter <= (ClkCounter + 1);
        end
    end
end

endmodule
