// File: CLAS2B4.v
// Generated by MyHDL 0.10
// Date: Sun Aug 19 09:07:52 2018


`timescale 1ns/10ps

module CLAS2B4 (
    P,
    G,
    cin,
    C
);


input [3:0] P;
input [3:0] G;
input cin;
output [3:0] C;
wire [3:0] C;

wire C4_i;
wire C3_i;
wire C2_i;
wire C1_i;


