// File: CLAS1_TBV.v
// Generated by MyHDL 0.10
// Date: Tue Aug 21 12:52:30 2018


`timescale 1ns/10ps

module CLAS1_TBV (

);
// myHDL -> Verilog Testbench for module "CLAS1"


reg x1 = 0;
reg x2 = 0;
wire [3:0] x1TVals;
wire [3:0] x2TVals;
wire p;
wire g;

assign x1TVals = 4'd3;
assign x2TVals = 4'd5;


always @(p, x2, g, x1) begin: CLAS1_TBV_PRINT_DATA
    $write("%h", x1);
    $write(" ");
    $write("%h", x2);
    $write(" ");
    $write("%h", p);
    $write(" ");
    $write("%h", g);
    $write("\n");
end



assign p = (x1 ^ x2);
assign g = (x1 & x2);


initial begin: CLAS1_TBV_STIMULES
    integer i;
    for (i=0; i<4; i=i+1) begin
        x1 <= x1TVals[i];
        x2 <= x2TVals[i];
        # 1;
    end
    $finish;
end

endmodule
