// File: CLAS3_TBV.v
// Generated by MyHDL 0.10
// Date: Tue Aug 21 12:52:32 2018


`timescale 1ns/10ps

module CLAS3_TBV (

);
// myHDL -> Verilog Testbench for module "CLAS3"


wire s;
reg c = 0;
reg p = 0;
wire [3:0] pTVals;
wire [3:0] cTVals;

assign pTVals = 4'd3;
assign cTVals = 4'd5;


always @(p, s, c) begin: CLAS3_TBV_PRINT_DATA
    $write("%h", p);
    $write(" ");
    $write("%h", c);
    $write(" ");
    $write("%h", s);
    $write("\n");
end



assign s = (p ^ c);


initial begin: CLAS3_TBV_STIMULES
    integer i;
    for (i=0; i<4; i=i+1) begin
        p <= pTVals[i];
        c <= cTVals[i];
        # 1;
    end
    $finish;
end

endmodule
