// File: CLAS1.v
// Generated by MyHDL 0.10
// Date: Tue Aug 21 12:52:29 2018


`timescale 1ns/10ps

module CLAS1 (
    x1,
    x2,
    p,
    g
);
// Carry Look Ahead Adder Stage One
// Input:
//     x1(bool): x1 input
//     x2(bool): x2 input
// 
// Output:
//     p(bool):carry propagate
//     g(bool):carry generate

input x1;
input x2;
output p;
wire p;
output g;
wire g;





assign p = (x1 ^ x2);
assign g = (x1 & x2);

endmodule
