// File: FullAdder.v
// Generated by MyHDL 0.10
// Date: Tue Aug 21 12:52:15 2018


`timescale 1ns/10ps

module FullAdder (
    x1,
    x2,
    cin,
    s,
    c
);
// Full Adder 2bit+1 input from exspresion
// Input:
//     x1(bool): bit signal to be added
//     x2(bool): bit signal to be added
//     cin(bool): carry in bit signal
// 
// Output:
//     s(bool): Full Adder Sum
//     c(bool): Full Adder Carry

input x1;
input x2;
input cin;
output s;
wire s;
output c;
wire c;





assign s = ((x1 ^ x2) ^ cin);
assign c = (((x1 & x2) | (x1 & cin)) | (x2 & cin));

endmodule
