// File: FullAdderViaHAs.v
// Generated by MyHDL 0.10
// Date: Tue Aug 21 12:52:18 2018


`timescale 1ns/10ps

module FullAdderViaHAs (
    x1,
    x2,
    cin,
    s,
    c
);
// Full Adder 2bit+1 input from Half Adders
// Input:
//     x1(bool): bit signal to be added
//     x2(bool): bit signal to be added
//     cin(bool): carry in bit signal
// 
// Output:
//     s(bool): Full Adder Sum
//     c(bool): Full Adder Carry

input x1;
input x2;
input cin;
output s;
wire s;
output c;
wire c;

wire s_HA1HA2;
wire c_HA1CL;
wire c_HA2CL;




assign s_HA1HA2 = (x1 ^ x2);
assign c_HA1CL = (x1 & x2);



assign s = (cin ^ s_HA1HA2);
assign c_HA2CL = (cin & s_HA1HA2);



assign c = (c_HA1CL | c_HA2CL);

endmodule
