// File: HalfAdder_TBV.v
// Generated by MyHDL 0.10
// Date: Tue Aug 21 12:52:14 2018


`timescale 1ns/10ps

module HalfAdder_TBV (

);
// myHDL -> Verilog Testbench for module "HalfAdder"


reg x1 = 0;
reg x2 = 0;
wire s;
wire c;
wire [3:0] x1TVals;
wire [3:0] x2TVals;

assign x1TVals = 4'd3;
assign x2TVals = 4'd5;


always @(s, x2, c, x1) begin: HALFADDER_TBV_PRINT_DATA
    $write("%h", x1);
    $write(" ");
    $write("%h", x2);
    $write(" ");
    $write("%h", s);
    $write(" ");
    $write("%h", c);
    $write("\n");
end



assign s = (x1 ^ x2);
assign c = (x1 & x2);


initial begin: HALFADDER_TBV_STIMULES
    integer i;
    for (i=0; i<4; i=i+1) begin
        x1 <= x1TVals[i];
        x2 <= x2TVals[i];
        # 1;
    end
    $finish;
end

endmodule
