// File: HalfAdder.v
// Generated by MyHDL 0.10
// Date: Tue Aug 21 12:52:14 2018


`timescale 1ns/10ps

module HalfAdder (
    x1,
    x2,
    s,
    c
);
// Half Adder
// Input:
//     x1(bool): bit signal to be added
//     x2(bool): bit signal to be added
// 
// Output:
//     s(bool): Half Adder Sum
//     c(bool): Half Adder Carry

input x1;
input x2;
output s;
wire s;
output c;
wire c;





assign s = (x1 ^ x2);
assign c = (x1 & x2);

endmodule
