// File: DEMUX1_4_Combo.v
// Generated by MyHDL 0.10
// Date: Sun Sep 23 18:24:17 2018


`timescale 1ns/10ps

module DEMUX1_4_Combo (
    x,
    s0,
    s1,
    y0,
    y1,
    y2,
    y3
);
// 1:4 DEMUX written in full combo
// 
// Inputs:
//     x(bool): input feed
//     s0(bool): channel select 0
//     s1(bool): channel select 1
// 
// Outputs:
//     y0(bool): ouput channel 0
//     y1(bool): ouput channel 1
//     y2(bool): ouput channel 2
//     y3(bool): ouput channel 3

input x;
input s0;
input s1;
output y0;
wire y0;
output y1;
wire y1;
output y2;
wire y2;
output y3;
wire y3;





assign y0 = ((!s0) && (!s1) && x);
assign y1 = (s0 && (!s1) && x);
assign y2 = ((!s0) && s1 && x);
assign y3 = (s0 && s1 && x);

endmodule
