// File: MUX2_1_Combo.v
// Generated by MyHDL 0.10
// Date: Sun Sep 23 18:19:36 2018


`timescale 1ns/10ps

module MUX2_1_Combo (
    x0,
    x1,
    s,
    y
);
// 2:1 Multiplexer written in full combo
// Input:
//     x0(bool): input channel 0
//     x1(bool): input channel 1
//     s(bool): channel selection input 
// Output:
//     y(bool): ouput

input x0;
input x1;
input s;
output y;
wire y;





assign y = (((!s) && x0) | (s && x1));

endmodule
