// File: ROMParmLoadSync.v
// Generated by MyHDL 0.10
// Date: Tue Jun 26 23:45:38 2018


`timescale 1ns/10ps

module ROMParmLoadSync (
    addr,
    dout,
    clk,
    rst
);
// A ROM laoded with data from CONTENT input tuple
// 
// I/O:
//     addr(Signal>4): addres; range is from 0-3
//     dout(Signal>4): data at each address
//     clk (bool): clock feed
//     rst (bool): reset
// Parm:
//     CONTENT: tuple size 4 with contende must be no larger then 4bit

input [3:0] addr;
output [3:0] dout;
reg [3:0] dout;
input clk;
input rst;




always @(posedge clk) begin: ROMPARMLOADSYNC_READACTION
    if (rst) begin
        dout <= 0;
    end
    else begin
        case (addr)
            0: dout <= 3;
            1: dout <= 2;
            2: dout <= 1;
            default: dout <= 0;
        endcase
    end
end

endmodule
