// File: PIPO_AS1.v
// Generated by MyHDL 0.10
// Date: Wed Sep  5 07:50:17 2018


`timescale 1ns/10ps

module PIPO_AS1 (
    DataIn,
    DataOut1,
    DataOut2
);
// 1:2 PIPO shift regestor with no clock (Asynchronous) 
// 
// Input:
//     DataIn(bitvec)
// Output:
//     DataOut1(bitVec): ouput one bitvec len should be same as 
//         `DataIn`
//     DataOut2(bitVec):ouput two bitvec len should be same as 
//         `DataIn`

input [3:0] DataIn;
output [3:0] DataOut1;
wire [3:0] DataOut1;
output [3:0] DataOut2;
wire [3:0] DataOut2;





assign DataOut1 = DataIn;
assign DataOut2 = DataIn;

endmodule
