// File: PISO.v
// Generated by MyHDL 0.10
// Date: Wed Sep  5 07:50:56 2018


`timescale 1ns/10ps

module PISO (
    ReadBus,
    BusIn,
    SerialOut,
    clk,
    rst
);
// Parallel In Serial Out right shift regestor
// 
// Input:
//     ReadBus(bool): read bus flag
//     BusIn(bool): Serial wire input
//     clk(bool): clock
//     rst(bool): reset
//     
// Output:
//     SerialOut(bool): Serial(wire) output data from `BusIn`
// Note:
//     Does not have a finsh serial write indicator 

input ReadBus;
input [3:0] BusIn;
output SerialOut;
wire SerialOut;
input clk;
input rst;

reg [3:0] Buffer;



always @(posedge clk, negedge rst) begin: PISO_LOGIC
    if (rst) begin
        Buffer <= 0;
    end
    else if (ReadBus) begin
        Buffer <= BusIn;
    end
    else begin
        Buffer <= (Buffer >>> 1);
    end
end



assign SerialOut = Buffer[0];

endmodule
