// File: SIPO.v
// Generated by MyHDL 0.10
// Date: Wed Sep  5 07:52:43 2018


`timescale 1ns/10ps

module SIPO (
    SerialIn,
    BusOut,
    clk,
    rst
);
// Serial In Parallel Out right shift regestor
// 
// Input:
//     SerialIn(bool): Serial wire input
//     clk(bool): clock
//     rst(bool): reset
//     
// Output:
//     BusOut(bitVec): Parallel(Bus) output data from `SerialWire`

input SerialIn;
output [3:0] BusOut;
wire [3:0] BusOut;
input clk;
input rst;

reg [3:0] Buffer = 0;



always @(posedge clk, negedge rst) begin: SIPO_LOGIC
    if (rst) begin
        Buffer <= 0;
    end
    else begin
        Buffer <= {Buffer[4-1:0], SerialIn};
    end
end



assign BusOut = Buffer;

endmodule
