// File: SISO.v
// Generated by MyHDL 0.10
// Date: Wed Sep  5 07:51:08 2018


`timescale 1ns/10ps

module SISO (
    SerialIn,
    SerialOut,
    clk,
    rst
);
// SISO Left Shift registor
// 
// Input:
//     SerialIn(bool): serial input feed
//     clk(bool): clock signal
//     rst(bool):reset signal
// 
// Output:
//     SerialOut(bool): serial out delayed by BufferSize
// 
// Paramter:
//     BufferSize(int): size of SISO buffer, aka delay amount

input SerialIn;
output SerialOut;
wire SerialOut;
input clk;
input rst;

reg [3:0] Buffer;



always @(posedge clk, negedge rst) begin: SISO_LOGIC
    if (rst) begin
        Buffer <= 0;
    end
    else begin
        Buffer <= {Buffer[(4 - 1)-1:0], SerialIn};
    end
end



assign SerialOut = Buffer[(4 - 1)];

endmodule
