// File: AndGate.v
// Generated by MyHDL 0.10
// Date: Sun Sep  2 00:45:15 2018


`timescale 1ns/10ps

module AndGate (
    X0,
    X1,
    Y
);
// And Gate demo module
// 
// Input:
//     X0(bool): And gate input 0
//     X1(bool): And gate input 1
// 
// Output:
//     Y(bool): And gate ouput 

input X0;
input X1;
output Y;
wire Y;





assign Y = (X0 && X1);

endmodule
