// File: NotGate_TBV.v
// Generated by MyHDL 0.10
// Date: Sun Sep  2 00:44:47 2018


`timescale 1ns/10ps

module NotGate_TBV (

);
// myHDL -> Verilog testbench for module `NotGate`


wire Y;
reg X = 0;
wire [9:0] XTV;

assign XTV = 10'd560;


always @(X, Y) begin: NOTGATE_TBV_PRINT_DATA
    $write("%h", X);
    $write(" ");
    $write("%h", Y);
    $write("\n");
end



assign Y = (!X);


initial begin: NOTGATE_TBV_STIMULES
    integer i;
    for (i=0; i<10; i=i+1) begin
        X <= XTV[i];
        # 1;
    end
    $finish;
end

endmodule
