// File: WireHigh.v
// Generated by MyHDL 0.10
// Date: Sun Sep  2 00:42:19 2018


`timescale 1ns/10ps

module WireHigh (
    Y
);
// Wire to Constatnt High
// Input:
//     None
// Output:
//     Y(bool): output

output Y;
wire Y;

wire HSource;

assign HSource = 1'd1;



assign Y = HSource;

endmodule
