// File: XNOrGate.v
// Generated by MyHDL 0.10
// Date: Mon Sep  3 14:50:48 2018


`timescale 1ns/10ps

module XNOrGate (
    X0,
    X1,
    Y
);
// XNOR Gate demo module
// 
// Input:
//     X0(bool): XOR gate input 0
//     X1(bool): XOR gate input 1
// 
// Output:
//     Y(bool): XOR gate ouput 

input X0;
input X1;
output Y;
wire Y;





assign Y = (!(X0 ^ X1));

endmodule
