// File: XorGate.v
// Generated by MyHDL 0.10
// Date: Sun Sep  2 00:46:25 2018


`timescale 1ns/10ps

module XorGate (
    X0,
    X1,
    Y
);
// XOR Gate demo module
// 
// Input:
//     X0(bool): XOR gate input 0
//     X1(bool): XOR gate input 1
// 
// Output:
//     Y(bool): XOR gate ouput 

input X0;
input X1;
output Y;
wire Y;





assign Y = (X0 ^ X1);

endmodule
