// File: RAMConcur.v
// Generated by MyHDL 0.10
// Date: Wed Jun 27 00:31:42 2018


`timescale 1ns/10ps

module RAMConcur (
    addr,
    din,
    writeE,
    dout,
    clk
);
// Random access read write memeory
// I/O:
//     addr(signal>4): the memory cell arrdress
//     din (signal>4): data to write into memeory
//     writeE (bool): write enable contorl; false is read only
//     dout (signal>4): the data out
//     clk (bool): clock
//     
// Note:
//     this is only a 4 byte memory

input [3:0] addr;
input [3:0] din;
input writeE;
output [3:0] dout;
wire [3:0] dout;
input clk;

reg [3:0] memory [0:4-1];

initial begin: INITIALIZE_MEMORY
    integer i;
    for(i=0; i<4; i=i+1) begin
        memory[i] = 0;
    end
end




always @(posedge clk) begin: RAMCONCUR_WRITEACTION
    if (writeE) begin
        memory[addr] <= din;
    end
end



assign dout = memory[addr];

endmodule
