// File: ROMLoaded.v
// Generated by MyHDL 0.10
// Date: Wed Jun 27 16:44:05 2018


`timescale 1ns/10ps

module ROMLoaded (
    addr,
    dout
);
// A ROM laoded with data already incoded in the structer
// insted of using myHDL inchanced parmter loading
// 
// I/O:
//     addr(Signal>4): addres; range is from 0-3
//     dout(Signal>4): data at each address

input [3:0] addr;
output [3:0] dout;
reg [3:0] dout;




always @(addr) begin: ROMLOADED_READACTION
    case (addr)
        'h0: begin
            dout = 3;
        end
        'h1: begin
            dout = 2;
        end
        'h2: begin
            dout = 1;
        end
        'h3: begin
            dout = 0;
        end
    endcase
end

endmodule
