// File: ROMLoaded_TBV.v
// Generated by MyHDL 0.10
// Date: Wed Jun 27 16:44:08 2018


`timescale 1ns/10ps

module ROMLoaded_TBV (

);
// Verilog Only Testbench  for `ROMLoaded`


reg [3:0] addr = 0;
reg [3:0] dout = 0;
reg clk = 0;



always @(addr) begin: ROMLOADED_TBV_ROMLOADED0_0_READACTION
    case (addr)
        'h0: begin
            dout = 3;
        end
        'h1: begin
            dout = 2;
        end
        'h2: begin
            dout = 1;
        end
        'h3: begin
            dout = 0;
        end
    endcase
end


initial begin: ROMLOADED_TBV_CLK_SIGNAL
    while (1'b1) begin
        clk <= (!clk);
        # 10;
    end
end


initial begin: ROMLOADED_TBV_STIMULES
    integer i;
    for (i=0; i<(3 + 1); i=i+1) begin
        addr <= i;
        @(posedge clk);
    end
    $finish;
end


always @(posedge clk) begin: ROMLOADED_TBV_PRINT_DATA
    $write("%h", addr);
    $write(" ");
    $write("%h", dout);
    $write("\n");
end

endmodule
